{% set data = load_setup_py_data() %}
{% set name = "mmviewer" %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

source:
  path: ..

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pyvcf
    - pandas
    - numpy
    - bcftools
    - joblib
    - bcftools
    - biopython
    - matplotlib
    - samtools
    - prodigal
    - blast
    - snpeff

test:
  commands:
    - mmviewer -h
    - mmviewer get_target -h
    - mmviewer alignment -h
    - mmviewer gen_graph -h

  about:
    home: https://github.com/KIkebata/mmviewer
    license: GPLv3
    summary: 'A graph showing tools to grasp patern of mutations, especially missense mutations in CDS, from short reads'
    license_family: GPL
