{% set data = load_setup_py_data() %}
{% set name = "mmviewer" %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

source:
  path: .

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv
  entry_points:
    - mmviewer = mmviwer.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pyvcf
    - pandas
    - bcftools
    - joblib
    - bcftools
    - biopython
    - matplotlib
    - samtools
    - prodigal
    - blast
    - snpeff
