{% set version = "0.0.1" %}
{% set name = "MMViewer" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ./mmviewer

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3.7
  run:
    - python >=3.7
    - pyvcf
    - pandas
    - bcftools
    - joblib
    - bcftools
    - biopython
    - matplotlib
    - samtools
    - prodigal
    - blast
    - snpeff
